config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/viewlist'

  root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def viewlist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter - Through Their Eyes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container-fluid">
  <div class="navbar-header">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag("brand.svg", :alt => "Brand") %>
      </a>
    </div>
</div>

</nav>
<main role="main">
  <%= yield %>
</main>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
  (function($) {
    var everyoneList = $('.js-everyone'),
        count = $('.js-everyone').children().length,
        childElement = everyoneList.find('li:first'),
        fudge = 40, // there is a 30-ish pixes padding to the left of the body container...this accounts for that plus a little breathing room
        width = count * childElement.outerWidth(true);

    $('body').css('width', width + fudge);

  })($.noConflict());
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-21407577-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Twitter: Through their eyes</h1>
            <h3>View the Twitter feeds of famous startup investors and entrepreneurs</h3>
            <br>
            <div class="text-center">
              <%=link_to "Check it out", pages_viewlist_path, class: "btn btn-primary btn-lg"%>
            </div>

            <h3>Why?</h3>

            <p>I've always been fascinated by discrepancies of information, the different classes of information we find ourselves plugged into, and how that affects our thoughts, feelings, and behaviors.</p>

            <p>When I lived in Ukraine and spoke with the older generation there, I was shocked to learn that many of them revered Stalin and Lenin as those born and raised in the United States would revere George Washington and Abraham Lincoln. This was a major shock to my system. To someone who grew up in the US, Stalin and Lenin were usually grouped with Hitler and Mussolini in the history books. This curiosity is one of the reasons I went on to start <a href="https://grasswire.com">Grasswire</a>).</p>

            <p>One of the main places I get information today is Twitter. So I wanted to see what Twitter looks like through the eyes of some of the most famous investors and entrepreneurs. I created a list of the people they follow, and find the results fascinating. Using Twitter's API it wasn't difficult to create a site to give everyone a glance without forcing them to go through all the same legwork that I did.</p>

            <p>The difficult part was coming up with a list of who to include. I tried looking for a good list, but in the end I just added whoever came to mind. You'll notice obvious groupings (for example, A16Z). That's probably a result of my train of thought; they're not necessarily ranked in order of perceived value.</p>

            <h3>How?</h3>

            The entire site is just Twitter widgets generated from lists.

            The lists were generated by scraping everyone followed by the entrepreneur/investor using <a href="http://electoralhq.com">ElectoralHQ</a>.

            The result is that you can see exactly what their feed is.

            <!--Attributing the noun project-->
            <br><br><br><br>
            <small>icon by Hysen Drogu from the Noun Project</small>
        </div>
    </div>
</div>
<!--Add a fork me on github ribbon-->
<a href="https://github.com/austenallred/theireyes"><img style="position: absolute; top: 0; right: 0; border: 0;z-index:9999" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

app/views/pages/viewlist.html.erb
<ul class="top-list"><li>
      <a class="twitter-share-button"
      href="http://theireyes.austenallred.com/pages/viewlist"
      data-via="austenallred">
    Tweet
    </a>
    <script>
    window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
    </script>
</li>

<li>
  Note: If you're just seeing a list of accounts, you probably need to turn off adblock. Unfortunately, no way around this.<br>

  Click on the list name (e.g. 'pmarca') to see natively on Twitter or subscribe to the list.
</li></ul>
<ul class="everyone clearfix js-everyone">
  
  <li>
    <!--pmarca -->
    <h2><a href="https://twitter.com/pmarca">Marc Andreessen</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/pmarca" data-widget-id="582539204007096321"></a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

    <!--marissa mayer -->
  <li>
    <h2><a href="https://twitter.com/marissamayer">Marissa Mayer</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/marissamayer" data-widget-id="582641895970484224">Tweets from https://twitter.com/AustenAllred/lists/marissamayer</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

  <li>
    <!--msuster-->
    <h2><a href="https://twitter.com/msuster">Mark Suster</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/msuster" data-widget-id="582562232204050432">Tweets from https://twitter.com/AustenAllred/lists/msuster</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--cdixon-->
    <h2><a href="https://twitter.com/cdixon">Chris Dixon</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/cdixon" data-widget-id="582539866619035648"></a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

  <li>
    <!--ev-->
    <h2><a href="https://twitter.com/ev">Evan Williams</a></h2>
    <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/AustenAllred/lists/ev" data-widget-id="582559581273899008">Tweets from https://twitter.com/AustenAllred/lists/ev</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--jack-->
    <h2><a href="https://twitter.com/jack">Jack Dorsey</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/jack" data-widget-id="582565324077203456">Tweets from https://twitter.com/AustenAllred/lists/jack</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

  <!--aileenlee-->
  <li>  
    <h2><a href="https://twitter.com/aileenlee">Aileen Lee</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/aileenlee" data-widget-id="582644942213795841">Tweets from https://twitter.com/AustenAllred/lists/aileenlee</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

  <li>
    <!--sacca-->
    <h2><a href="https://twitter.com/sacca">Chris Sacca</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/sacca" data-widget-id="582566281087303681">Tweets from https://twitter.com/AustenAllred/lists/sacca</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--fred wilson-->
    <h2><a href="https://twitter.com/fredwilson">Fred Wilson</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/fredwilson" data-widget-id="582567076784578560">Tweets from https://twitter.com/AustenAllred/lists/fredwilson</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--startup l jackson-->
    <h2><a href="https://twitter.com/startupljackson">Startup L Jackson</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/startupljackson" data-widget-id="582568167236456449">Tweets from https://twitter.com/AustenAllred/lists/startupljackson</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--benedict evans-->
    <h2><a href="https://twitter.com/benedictevans">Benedict Evans</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/benedictevans" data-widget-id="582568577301020672">Tweets from https://twitter.com/AustenAllred/lists/benedictevans</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--paul graham-->
    <h2><a href="https://twitter.com/paulg">Paul Graham</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/paulg" data-widget-id="582571345923301376">Tweets from https://twitter.com/AustenAllred/lists/paulg</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--aaron levie-->
    <h2><a href="https://twitter.com/levie">Aaron Levie</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/levie" data-widget-id="582571851613757441">Tweets from https://twitter.com/AustenAllred/lists/levie</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--ryan hoover-->
    <h2><a href="https://twitter.com/rrhoover">Ryan Hoover</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/rhoover" data-widget-id="582572427433005057">Tweets from https://twitter.com/AustenAllred/lists/rhoover</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--hunter walk-->
    <h2><a href="https://twitter.com/hunterwalk">Hunter Walk</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/hunterwalk" data-widget-id="582573166762971136">Tweets from https://twitter.com/AustenAllred/lists/hunterwalk</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

<!--jessica livingston-->
  <li>
    <h2><a href="https://twitter.com/foundersatwork">Jessica Livingston</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/foundersatwork" data-widget-id="582647835075579904">Tweets from https://twitter.com/AustenAllred/lists/foundersatwork</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>

  <li>
    <!--travis kalanick-->
    <h2><a href="https://twitter.com/travisk">Travis Kalanick</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/travisk" data-widget-id="582574330904625152">Tweets from https://twitter.com/AustenAllred/lists/travisk</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--ben rubin-->
    <h2><a href="https://twitter.com/benrbn">Ben Rubin</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/benrbn" data-widget-id="582575156901511168">Tweets from https://twitter.com/AustenAllred/lists/benrbn</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--bryce roberts-->
    <h2><a href="https://twitter.com/bryce">Bryce Roberts</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/bryce" data-widget-id="582576013231542272">Tweets from https://twitter.com/AustenAllred/lists/bryce</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--stewart butterfield-->
    <h2><a href="https://twitter.com/stewart">Stewart Butterfield</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/stewart" data-widget-id="582576389489979392">Tweets from https://twitter.com/AustenAllred/lists/stewart</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  <li>
    <!--ben horowitz-->
    <h2><a href="https://twitter.com/bhorowitz">Ben Horowitz</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/bhorowitz" data-widget-id="582577687719362560">Tweets from https://twitter.com/AustenAllred/lists/bhorowitz</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
  


   
<!--jessica lessin-->
   <li>
    <h2><a href="https://twitter.com/jessicalessin">Jessica Lessin</a></h2>
    <a class="twitter-timeline" href="https://twitter.com/AustenAllred/lists/jessicalessin1" data-widget-id="582645826356301825">Tweets from https://twitter.com/AustenAllred/lists/jessicalessin1</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>